DATA_LINK="https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
python -m mytorch.distributed.launch --num_gpus 2 --training_script train_ddp_tiny_gpt2.py \
    --context_length 512 \
    --embed_dim 512 \
    --num_heads 8 \
    --num_blocks 8 \
    --dropout_p 0.1 \
    --mlp_ratio 4 \
    --data_path $DATA_LINK \
    --train_iterations 2500 \
    --warmup_steps 250 \
    --batch_size 32 \
    --max_lr "3e-4" \
    --min_lr "5e-5" \
    --weight_decay 0.1 \
    --max_grad_norm 1.0 \
    --gradient_accumulation 1 \
    --log_iter 100 \
    --gen_iter 500 \
    --gen_length 256 \
    --save_path "work_dir/char_shakespear_gpt2.safetensors"
